---
abstract: 'L<Dist::Zilla> plugins for ARJONES'
author:
  - 'Andrew Jones <andrew@arjones.co.uk>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-ARJONES
requires:
  Dist::Zilla: 2.100922
  Dist::Zilla::App::Command::cover: 0
  Dist::Zilla::App::Command::perltidy: 0
  Dist::Zilla::Plugin::Clean: 0
  Dist::Zilla::Plugin::ContributorsFromGit: 0
  Dist::Zilla::Plugin::GithubMeta: 0
  Dist::Zilla::Plugin::NoSmartCommentsTests: 0
  Dist::Zilla::Plugin::NoTabsTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::Test::Compile: 0
  Dist::Zilla::Plugin::Test::Kwalitee: 0
  Dist::Zilla::Plugin::Test::Perl::Critic: 0
  Dist::Zilla::Plugin::Test::Pod::No404s: 0
  Dist::Zilla::Plugin::Test::Portability: 0
  Dist::Zilla::PluginBundle::Basic: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  Moose::Autobox: 0
  Pod::Coverage::TrustPod: 0
  Pod::Elemental::Transformer::List: 0
  Pod::Weaver::Config::Assembler: 0
  Pod::Weaver::Plugin::Encoding: 0
  Pod::Weaver::Section::Contributors: 0.001
  Test::NoSmartComments: 0
  Test::Perl::Critic: 0
  Test::Pod: 1.41
  Test::Pod::Coverage: 1.08
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/andrewrjones/perl5-Dist-Zilla-PluginBundle-ARJONES/issues
  homepage: https://github.com/andrewrjones/perl5-Dist-Zilla-PluginBundle-ARJONES
  repository: https://github.com/andrewrjones/perl5-Dist-Zilla-PluginBundle-ARJONES.git
version: 1.130720
x_contributors:
  - 'Andrew Jones <andrew.jones@arm.com>'
  - 'Andrew Jones <andrewjones86@googlemail.com>'
  - 'andrewrjones <andrewjones86@googlemail.com>'
